LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := Torch
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := Torch.apk

LOCAL_PACKAGE_NAME := Torch.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
include $(BUILD_PREBUILT)

